### ISSUE TITLE
Negative Money.

### ISSUE THREAD

**Issue by Detoxz** [lilfuchs/esx_lscustomsV2#1]
When you do not have the sufficient funds, instead of canceling the purchase , it sets your balance negative allowing free upgrades and a problem with the economy. 

https://cdn.discordapp.com/attachments/344225663341035540/473040447883968532/unknown.png

**Comment by OhTanoshi** [comment]
Ill get this fixed in a few.

**Comment by OhTanoshi** [comment]
This should be fixed now.

**Comment by OhTanoshi** [comment]
The issue was not fixed infact i had broke it. Weird how something works and then breaks a few mins latet. anyways newest commit fixed it competely.

**Comment by Detoxz** [comment]
This issue still persists.

![image](https://user-images.githubusercontent.com/41855089/43371242-b59f5662-935b-11e8-917e-f5909fcf3273.png)

**Comment by OhTanoshi** [comment]
Sorry, forgot to commit the new update earlier its now fixed
